# -*- coding: utf-8 -*-
"""FUNÇÕES(PARTE 01).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdt95IxJcND3ejshqFy99AgO5MOZuaVz

Primeiro exemplo 01 -
"""

a = 4
b = 5
s = a + b
print(s) #Aqui vai mostrar 9 

a = 8
b = 9
s = a + b
print(s) #Aqui vai mostrar 17

a = 2
b = 1
s = a + b
print(s) #Aqui vai mostrar 3
print('-' * 30)

#Realizar a mesma soma utilizando funções ou sejá rotinas

def soma(a, b): #Sempre pular duas linhas depois do def
  print(f'A = {a} e B = {b}')
  s = a + b
  print(f'A soma A + B = {s}')


#Programa principal
soma(4, 5) #O 4 e 5 são parametros que estaram sendo inseridas no "a" e "b"
soma(8, 9) #O 8 e 9 são parametros que estaram sendo inseridas no "a" e "b"
soma(2, 1) #O 2 e 1 são parametros que estaram sendo inseridas no "a" e "b"

#Posso fazer dessa forma também
soma(a=4, b= 5)
soma(b=8, a=9) #também posso mudar a ordem,
soma(a=2, b=1)

"""Outro exemplo - Aqui e desempacotar"""

def contador(*num):
  for valor in num: #Para cada valor em num
    print(f'{valor}' , end='')
  print(' FIM')


contador(2, 1, 7)
contador(8, 0)
contador(4, 4, 7, 6, 2)

"""Outro exemplo"""

def contador(* num):
  tam = len(num) #O len de num e quantos elementos ele tem
  print(f'Recebi os valores {num} e são ao todo {tam} números')


contador(2, 1, 7) #Tuplas
contador(8, 0)
contador(4, 4, 7, 6, 2)

"""Outro exemplo"""

def dobra(lista):
  pos = 0
  while pos < len(lista):
    lista[pos]*=2
    pos = pos +1

valores = [7,2,5,0,4] #Criando a lista
dobra(valores)
print(valores)

"""Exemplo utilizando desempacotamento"""

def soma(* valores):
  s = 0
  for num in valores: #Para cada elemento(num) em valores
    s += num
  print(f'Somando os valores {valores} temos {s}')



soma(5, 2)
soma(2, 9, 4)