# -*- coding: utf-8 -*-
"""LISTAS(PARTE 02).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PN8qlqUqSURQIZua8Ej0Hwt29rUgrgx
"""

teste = list() # Criando uma lista chamada ''teste''
teste.append('Gustavo') #A dicionando um elemento
teste.append(40)
galera = list() #Criando outra lista chamada "galera"
galera.append(teste) #Aqui está fazendo uma ligação entre as listas
teste[0] = 'Maria'
teste[1] = 22
galera.append(teste)#Aqui está fazendo uma ligação entre as listas
print(teste)
print(galera)

"""Outro exemplo"""

teste = list() # Criando uma lista chamada ''teste''
teste.append('Gustavo') #A dicionando um elemento
teste.append(40)
galera = list() #Criando outra lista chamada "galera"
galera.append(teste[:]) #Aqui está fazendo uma copia entre as listas
teste[0] = 'Maria'
teste[1] = 22
galera.append(teste[:])#Aqui está fazendo uma copia entre as listas
print(teste)
print(galera)

"""Outro exemplo"""

galera = [['João',19],['Ana',33],['Joaquim',13],['Maria',45]] #Criando uma lista com 4 elementos
print(galera)
print(galera[0])
print(galera[0][0])
print(galera[2][1])

"""Outro exemplo"""

galera = [['João',19],['Ana',33],['Joaquim',13],['Maria',45]] #Criando uma lista com 4 elementos
for pessoa in galera:#Para cada pessoa em galera
  print(pessoa)
  print(f'{pessoa[0]}') #Pegando somente o nome
  print(f'{pessoa[1]}') #Pegando somente a idade
  print(f'{pessoa[0]} tem {pessoa[1]} anos de idade.')

"""Outro exemplo"""

galera = list()
dado = list()
for contador in range(0, 3):
  dado.append(str(input('Nome: ')))
  dado.append(int(input('Idade: ')))
  galera.append(dado[:])
  dado.clear()

print(galera)

"""Outro exemplo"""

galera = list() #Criando a primeira estrutura de dados (LISTA)
dado = list() #Criando outra estrutura de dados(LISTA).Estrutura de dados auxiliar que eu vou pegar os dados e depois mandar para a estrutura principal
totmai = totmen = 0 #Mesma coisa que fazer totmai = 0 e totmen = 0
for contador in range(0, 3):
  dado.append(str(input('Nome: ')))
  dado.append(int(input('Idade: ')))
  galera.append(dado[:])
  dado.clear() #Apaga os laços até

for pessoa in galera:
  if pessoa[1] >= 21:
    print(f'{pessoa[0]} é maior de idade.')
    totmai += 1 #totmai = totmai + 1
  else:
    print(f'{pessoa[0]} é menor de idade.')
    totmen += 1

print(f'Temos {totmai} maiores e {totmen} menores de idade.')
print(galera)