# -*- coding: utf-8 -*-
"""Listas(Parte01).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18CwBQvd_PIqmZf2_R5cQ5vTYO6M_0NuD

Criando uma Tupla
"""

num = (2, 5, 9, 1)
print(num)

"""Criando uma Lista"""

num = [2, 5, 9, 1]
num[2] = 3 #Aqui estou fazendo o indice 2 valer o valor 3.Vai deixar de valer 9 e passar a valer 3
num.append(7) #Estou adicionando o valor 7 ao elemento(lista)
num.sort() #Permite colocar a lista em ordem
print(num)

"""Outro exemplo de Lista"""

num = [2, 5, 9, 1]
num[2] = 3 #Aqui estou fazendo o indice 2 valer o valor 3.Vai deixar de valer 9 e passar a valer 3
num.append(7) #Estou adicionando o valor 7 ao elemento(lista)
num.sort(reverse=True) #Colocando a lista em ordem reversa
print(num)
print(f'Essa lista tem {len(num)} elementos') #Saber quantos elementos tem a lista

"""Outro exemplo de Lista"""

num = [2, 5, 9, 7]
num.insert(2,0) #Adicionando um valor.Na posição 2 vou inserir o valor 0
print(num)

"""Outro exemplo"""

num = [2, 5, 9, 7]
num.pop() #Removendo o ultimo elemento
num.pop(2) #Removendo o elemento que está na posição do indice 2, ou seja, o número 9
print(num)

"""Outro exemplo"""

num = [2, 5, 9, 1]
num.remove(2)#O remove procura do inicio da lista, a primeira ocorrencia do valor que você mando eliminar
print(num)

"""Outro exemplo"""

num = [2, 5, 9, 1]
if 5 in num: #Se o numero 5 estiver na lista num
  num.remove(5) #removendo da lista o número 5
else:#senão
  print('Não achei o número 5')
print(num)

"""Outro exemplo"""

#Posso começar uma lista vazia de duas maneiras
valores1 = [] #Primeira maneira de iniciar uma lista vazia
valores = list() #Segunda maneira de iniciar uma lista vazia
valores.append(5)
valores.append(9)
valores.append(4)
print(valores)

for valor in valores: # Para cada elemento da minha lista "valores"
  print(f'{valor}...',end='')

"""Outro exemplo:"""

valores = []
valores.append(5)
valores.append(2)
valores.append(1)
for chave, valor in enumerate(valores):
    print(f'Na posição {chave} encontrei o valor {valor}!')
print('Cheguei ao final da lista')

"""Outro exemplo"""

valores = list()
for cont in range(0, 5):
  valores.append(int(input('Digite um valor: ')))

for chave, valor in enumerate(valores):
    print(f'Na posição {chave} encontrei o valor {valor}!')
print('Cheguei ao final da lista')

"""Outro exemplo"""

a = [2, 3, 4, 7]
b = a #A partir do momento que eu igualo uma lista na outra,o python cria uma ligação entre elas
b[2] = 8
print(f'Lista A: {a}')
print(f'Lista B: {b}')

"""Outro exemplo:

"""

a = [2, 3, 4, 7]
b = a[:]#"B" vai receber todos os elementos de "A"."B" VAI RECEBER UMA COPIA DOS ELEMENTOS DE "A"
print(f'Lista A: {a}')
print(f'Lista B: {b}')